version: '3'
services:


  sn.db.mysql:
    container_name: sn.db.mysql
    ports:
      - '3306:3306'
    image: mysql
    env_file:
      - .env


  sn.db.redis:
    container_name: sn.db.redis
    image: redis
    ports:
      - '6379:6379'


  sn.front.public:
    build: ./frontend/public
    volumes:
      - './frontend/public/src:/app'


  sn.front.admin:
    build: ./frontend/admin
    volumes:
      - './frontend/admin/src:/app'

  sn.api:
    build: ./backend/api
    ports:
      - '8000:8000'
    volumes:
      - './backend/api/src:/app'
    depends_on:
      - sn.db.mysql
      - sn.db.redis


  sn.ngnix.router:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '81:81'
    depends_on:
      - sn.api
      - sn.front.admin
      - sn.front.public